# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          path: 'text-repo'
      - uses: actions/checkout@v2
        with:
          repository: hgspsz/theme
          path: 'theme-repo'
      - run: mkdir target
      - run: git init
      - run: cp -r ./text-repo/* ./target
      - run: cp -r ./theme-repo/* ./target
      - name: Install tree
        run: sudo apt-get install tree
      - run: tree .     
      - uses: jakejarvis/hugo-build-action@master
        with:
          args: --source target
      
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          local-dir: ./target/public
          ftp-server: ftp://harsanyisportpszichologus.hu/public_html
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure  
